export const CFSubmissionStatus = {
    "FAILED": "unknown_error",
    "OK": "accepted",
    "PARTIAL": "partial_accepted",
    "COMPILATION_ERROR": "compile_error",
    "RUNTIME_ERROR": "runtime_error",
    "WRONG_ANSWER": "wrong_answer",
    "TIME_LIMIT_EXCEEDED": "time_limit_exceeded",
    "MEMORY_LIMIT_EXCEEDED": "memory_limit_exceeded",
    "IDLENESS_LIMIT_EXCEEDED": "idleness_limit_exceeded",
    "SECURITY_VIOLATED": "dangerous_code",
    "CRASHED": "runtime_error",
    "INPUT_PREPARATION_CRASHED": "runtime_error",
    "CHALLENGED": "wrong_answer",
    "SKIPPED": "unknown_error",
    "TESTING": "waiting",
    "REJECTED": "unknown_error",
    "SUBMITTED": "waiting",
}