// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 分配任务请求
 */
export type AssignTaskReq = { vjudge_node_id: bigint, range: string, ws_id: string | null, };
