// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VjudgeAuth } from "./VjudgeAuth";

/**
 * 绑定账号请求
 */
export type BindAccountReq = { platform: string, method: string, auth: VjudgeAuth | null, bypass_check: boolean | null, ws_id: string | null, iden: string, };
