// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainingList } from "./TrainingList";

export type CreateTrainingReq = { iden: string, title: string, description_public: string, description_private: string, start_time: string, end_time: string, training_type: string, problem_list: TrainingList, write_perm_user: Array<bigint>, read_perm_user: Array<bigint>, };
