// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemStatementProp } from "./ProblemStatementProp";

export type CreateProblemProps = { user_id: bigint, problem_iden: string, problem_name: string, problem_statement: Array<ProblemStatementProp>, creation_time: string, tags: Array<string>, };
