// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgePlatformFieldInfo } from "./EdgePlatformFieldInfo";

export type EdgePlatformMethodInfo = { name: string, description: string, stable: number, require_fields: Array<EdgePlatformFieldInfo>, tips: Array<string> | null, is_pwd: boolean | null, payload_template: string, };
