// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupNodePublic = { name: string, description: string, creation_time: bigint, creation_order: bigint, avatar: string, };
