// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupNodePrivate } from "./GroupNodePrivate";
import type { GroupNodePublic } from "./GroupNodePublic";

export type GroupNode = { node_id: bigint, node_iden: string, public: GroupNodePublic, private: GroupNodePrivate, };
