// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdenNodePrivate } from "./IdenNodePrivate";
import type { IdenNodePublic } from "./IdenNodePublic";

export type IdenNode = { node_id: bigint, public: IdenNodePublic, private: IdenNodePrivate, };
