// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdenNodePrivateRaw } from "./IdenNodePrivateRaw";
import type { IdenNodePublicRaw } from "./IdenNodePublicRaw";

export type IdenNodeRaw = { public: IdenNodePublicRaw, private: IdenNodePrivateRaw, };
