// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileIOMethod } from "./FileIOMethod";

export type JudgeIOMethod = "Std" | { "FileIO": FileIOMethod } | "RemoteJudge";
