// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageChoiceOptionsInformation } from "./LanguageChoiceOptionsInformation";

export type LanguageChoiceInformation = { name: string, allow_option: Array<LanguageChoiceOptionsInformation>, };
