// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LanguageChoiceOptionsInformation = { name: string, is_compile: boolean, is_input: boolean, allowed_option: Array<string>, };
