// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PagesNodePrivate } from "./PagesNodePrivate";
import type { PagesNodePublic } from "./PagesNodePublic";

export type PagesNode = { node_id: bigint, public: PagesNodePublic, private: PagesNodePrivate, };
