// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PagesNodePrivateRaw } from "./PagesNodePrivateRaw";
import type { PagesNodePublicRaw } from "./PagesNodePublicRaw";

export type PagesNodeRaw = { iden: string, public: PagesNodePublicRaw, private: PagesNodePrivateRaw, };
