// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 参数类型
 */
export type ParamType = "String" | "Number" | { "Select": Array<string> };
