// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamType } from "./ParamType";

/**
 * 参数信息
 */
export type ParamInfo = { name: string, label: string, param_type: ParamType, required: boolean, default_value: string | null, };
