// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermGroupNodePrivateRaw } from "./PermGroupNodePrivateRaw";
import type { PermGroupNodePublicRaw } from "./PermGroupNodePublicRaw";

export type PermGroupNodeRaw = { iden: string, service: string, public: PermGroupNodePublicRaw, private: PermGroupNodePrivateRaw, };
