// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SimplyUser } from "./SimplyUser";

export type PermOwner = { "User": SimplyUser } | { "Group": string } | { "Unknown": bigint };
