// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermGroupNodePrivate } from "./PermGroupNodePrivate";
import type { PermGroupNodePublic } from "./PermGroupNodePublic";

export type PermGroupNode = { node_id: bigint, public: PermGroupNodePublic, private: PermGroupNodePrivate, };
