// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProblemListQuery = { page: bigint | null, per_page: bigint | null, name: string | null, tag: Array<string> | null, author: string | null, difficulty: [number, number] | null, };
