// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemLimitNodePrivate } from "./ProblemLimitNodePrivate";
import type { ProblemLimitNodePublic } from "./ProblemLimitNodePublic";

export type ProblemLimitNode = { node_id: bigint, public: ProblemLimitNodePublic, private: ProblemLimitNodePrivate, };
