// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemLimitNodePrivateRaw } from "./ProblemLimitNodePrivateRaw";
import type { ProblemLimitNodePublicRaw } from "./ProblemLimitNodePublicRaw";

export type ProblemLimitNodeRaw = { public: ProblemLimitNodePublicRaw, private: ProblemLimitNodePrivateRaw, };
