// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemSourceNodePrivate } from "./ProblemSourceNodePrivate";
import type { ProblemSourceNodePublic } from "./ProblemSourceNodePublic";

export type ProblemSourceNode = { node_id: bigint, public: ProblemSourceNodePublic, private: ProblemSourceNodePrivate, };
