// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemStatementNodePrivate } from "./ProblemStatementNodePrivate";
import type { ProblemStatementNodePublic } from "./ProblemStatementNodePublic";

export type ProblemStatementNode = { node_id: bigint, public: ProblemStatementNodePublic, private: ProblemStatementNodePrivate, };
