// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentType } from "./ContentType";

export type ProblemStatementProp = { statement_source: string, iden: string, problem_statements: Array<ContentType>, time_limit: bigint, memory_limit: bigint, sample_group: Array<[string, string]>, show_order: Array<string>, page_source: string | null, page_rendered: string | null, problem_difficulty: number | null, judge_option: { [key in string]?: string } | null, };
