// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemTagNodePrivate } from "./ProblemTagNodePrivate";
import type { ProblemTagNodePublic } from "./ProblemTagNodePublic";

export type ProblemTagNode = { node_id: bigint, public: ProblemTagNodePublic, private: ProblemTagNodePrivate, };
