// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemLimitNode } from "./ProblemLimitNode";
import type { ProblemNode } from "./ProblemNode";
import type { ProblemStatementNode } from "./ProblemStatementNode";
import type { ProblemTagNode } from "./ProblemTagNode";
import type { SimplyUser } from "./SimplyUser";

export type ProblemModel = { problem_node: ProblemNode, problem_statement_node: Array<[ProblemStatementNode, ProblemLimitNode]>, tag: Array<ProblemTagNode>, author: SimplyUser | null, };
