// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemNodePrivate } from "./ProblemNodePrivate";
import type { ProblemNodePublic } from "./ProblemNodePublic";

export type ProblemNode = { node_id: bigint, public: ProblemNodePublic, private: ProblemNodePrivate, };
