// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemNodePrivateRaw } from "./ProblemNodePrivateRaw";
import type { ProblemNodePublicRaw } from "./ProblemNodePublicRaw";

export type ProblemNodeRaw = { public: ProblemNodePublicRaw, private: ProblemNodePrivateRaw, };
