// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentType } from "./ContentType";

export type ProblemStatementNodePublicRaw = { statements: Array<ContentType>, source: string, iden: string, creation_time: string, sample_group_in: Array<string>, sample_group_out: Array<string>, page_source: string | null, page_rendered: string | null, problem_difficulty: number | null, show_order: Array<string>, };
