// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemSourceNodePrivateRaw } from "./ProblemSourceNodePrivateRaw";
import type { ProblemSourceNodePublicRaw } from "./ProblemSourceNodePublicRaw";

export type ProblemSourceNodeRaw = { public: ProblemSourceNodePublicRaw, private: ProblemSourceNodePrivateRaw, };
