// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordNewProp = { platform: string, code: string, code_language: string, url: string, statement_node_id: bigint, public_status: boolean, };
