// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordListQuery = { page: bigint | null, per_page: bigint | null, user: string | null, problem: string | null, status: bigint | null, platform: string | null, };
