// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordEdge } from "./RecordEdge";

export type RecordListItem = { edge: RecordEdge, problem_name: string, problem_iden: string, user_name: string, user_iden: string, };
