// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordStatus } from "./RecordStatus";

export type RecordNodePublicRaw = { record_score: bigint, record_platform: string, record_url: string | null, record_status: RecordStatus, record_message: string | null, record_time: string, statement_id: bigint, public_status: boolean, };
