// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordStatus } from "./RecordStatus";

export type RecordNodePublic = { record_order: bigint, record_score: bigint, record_platform: string, record_status: RecordStatus, record_message: string, record_time: string, record_update_time: string, code: string | null, code_language: string | null, record_url: string | null, };
