// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordNodePrivateRaw } from "./RecordNodePrivateRaw";
import type { RecordNodePublicRaw } from "./RecordNodePublicRaw";

export type RecordNodeRaw = { public: RecordNodePublicRaw, private: RecordNodePrivateRaw, };
