// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordStatus } from "./RecordStatus";

export type RecordEdge = { id: bigint, u: bigint, v: bigint, record_node_id: bigint, record_status: RecordStatus, code_length: bigint, score: bigint, submit_time: string, platform: string, };
