// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordNodePrivate } from "./RecordNodePrivate";
import type { RecordNodePublic } from "./RecordNodePublic";

export type RecordNode = { node_id: bigint, public: RecordNodePublic, private: RecordNodePrivate, };
