// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordStatus = "Accepted" | "Partial Accepted" | "Wrong Answer" | "Time Limit Exceeded" | "Memory Limit Exceeded" | "Output Limit Exceeded" | "Idleness Limit Exceeded" | "Runtime Error" | "Compile Error" | "DangerousCode" | "Remote Service Unknown Error" | "Sandbox Error" | "Remote Platform Refused" | "Remote Platform Connection Failed" | "Remote Platform Unknown Error" | "Waiting" | "Unknown Error" | "Deleted" | "OnlyArchived" | "NotFound" | "Skipped" | "Judging";
