// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SidebarItem = { title: string, url: string, show: string | null, reg: string | null, icon: string, number: bigint | null, };
