// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmitResultProp = { ws_id: string | null, success: boolean, remote_url: string | null, message: string | null, record_id: bigint, };
