// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 提交记录项
 */
export type SubmissionItem = { remote_id: bigint, remote_platform: string, remote_problem_id: string, language: string, code: string, status: string, message: string, score: bigint, submit_time: string, url: string, 
/**
 * (testcase_id, status, score, time, memory)
 */
passed: Array<[string, string, bigint, bigint, bigint]>, };
