// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubtaskCalcMethod } from "./SubtaskCalcMethod";

export type SubtaskNodePublic = { subtask_id: number, time_limit: bigint, memory_limit: bigint, subtask_calc_method: SubtaskCalcMethod, is_root: boolean, };
