// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubtaskNodePrivate } from "./SubtaskNodePrivate";
import type { SubtaskNodePublic } from "./SubtaskNodePublic";

export type SubtaskNode = { node_id: bigint, public: SubtaskNodePublic, private: SubtaskNodePrivate, };
