// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubtaskNodePrivateRaw } from "./SubtaskNodePrivateRaw";
import type { SubtaskNodePublicRaw } from "./SubtaskNodePublicRaw";

export type SubtaskNodeRaw = { public: SubtaskNodePublicRaw, private: SubtaskNodePrivateRaw, };
