// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordStatus } from "./RecordStatus";

export type SubtaskUserRecord = { time: bigint, memory: bigint, status: RecordStatus, subtask_status: Array<SubtaskUserRecord>, score: bigint, };
