// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamInfo } from "./ParamInfo";

/**
 * 终点信息
 */
export type TargetInfo = { name: string, display_name: string, description: string, required_params: Array<ParamInfo>, service_chain: Array<string>, };
