// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestcaseNodePrivateRaw } from "./TestcaseNodePrivateRaw";
import type { TestcaseNodePublicRaw } from "./TestcaseNodePublicRaw";

export type TestcaseNodeRaw = { public: TestcaseNodePublicRaw, private: TestcaseNodePrivateRaw, };
