// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestcaseNodePrivate } from "./TestcaseNodePrivate";
import type { TestcaseNodePublic } from "./TestcaseNodePublic";

export type TestcaseNode = { node_id: bigint, public: TestcaseNodePublic, private: TestcaseNodePrivate, };
