// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TestcaseNodePublic = { time_limit: bigint, memory_limit: bigint, in_file: bigint, out_file: bigint, testcase_name: string, };
