// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JudgeDiffMethod } from "./JudgeDiffMethod";
import type { JudgeIOMethod } from "./JudgeIOMethod";

export type TestcaseNodePrivate = { io_method: JudgeIOMethod, diff_method: JudgeDiffMethod, };
