// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenNodePrivate } from "./TokenNodePrivate";
import type { TokenNodePublic } from "./TokenNodePublic";

export type TokenNode = { node_id: bigint, public: TokenNodePublic, private: TokenNodePrivate, };
