// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenNodePrivateRaw } from "./TokenNodePrivateRaw";
import type { TokenNodePublicRaw } from "./TokenNodePublicRaw";

export type TokenNodeRaw = { iden: string, service: string, public: TokenNodePublicRaw, private: TokenNodePrivateRaw, };
