// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainingStatus } from "./TrainingStatus";

export type TrainingUserEdgeRaw = { u: bigint, v: bigint, status: TrainingStatus, };
