// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainingList } from "./TrainingList";

export type TrainingProblem = { "ProblemIden": [bigint, string, bigint] } | { "ProblemTraining": [bigint, TrainingList] } | { "ProblemPresetTraining": [bigint, string] } | { "ExistTraining": [bigint, string] };
