// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainingProblemNodePrivate } from "./TrainingProblemNodePrivate";
import type { TrainingProblemNodePublic } from "./TrainingProblemNodePublic";

export type TrainingProblemNode = { node_id: bigint, public: TrainingProblemNodePublic, private: TrainingProblemNodePrivate, };
