// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainingProblemNodePrivateRaw } from "./TrainingProblemNodePrivateRaw";
import type { TrainingProblemNodePublicRaw } from "./TrainingProblemNodePublicRaw";

export type TrainingProblemNodeRaw = { public: TrainingProblemNodePublicRaw, private: TrainingProblemNodePrivateRaw, };
