// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainingProblem } from "./TrainingProblem";

export type TrainingList = { node_id: bigint | null, description: string, own_problem: Array<TrainingProblem>, };
