// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainingNodePrivate } from "./TrainingNodePrivate";
import type { TrainingNodePublic } from "./TrainingNodePublic";

export type TrainingNode = { node_id: bigint, public: TrainingNodePublic, private: TrainingNodePrivate, };
