// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainingNodePrivateRaw } from "./TrainingNodePrivateRaw";
import type { TrainingNodePublicRaw } from "./TrainingNodePublicRaw";

export type TrainingNodeRaw = { public: TrainingNodePublicRaw, private: TrainingNodePrivateRaw, };
