// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainingProblemType } from "./TrainingProblemType";

export type TrainingProblemEdge = { id: bigint, u: bigint, v: bigint, order: bigint, problem_type: TrainingProblemType, };
