// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainingList } from "./TrainingList";
import type { TrainingNode } from "./TrainingNode";

export type Training = { training_node: TrainingNode, problem_list: TrainingList, };
