// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrainingNodePublic = { name: string, iden: string, description: string, start_time: string, end_time: string, training_type: string, };
