// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserNodePrivate } from "./UserNodePrivate";
import type { UserNodePublic } from "./UserNodePublic";

export type UserNode = { node_id: bigint, node_iden: string, public: UserNodePublic, private: UserNodePrivate, };
