// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserCreaterUserVerify = { challenge_text: string, challenge_darkmode: string, challenge_code: string, challenge_time: bigint, };
