// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserNodePrivateRaw } from "./UserNodePrivateRaw";
import type { UserNodePublicRaw } from "./UserNodePublicRaw";

export type UserNodeRaw = { public: UserNodePublicRaw, private: UserNodePrivateRaw, };
