// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserUpdateProps = { name: string | null, email: string | null, avatar: string | null, description: string | null, bio: string | null, user_profile_show: string | null, };
