// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserNodePublic = { name: string, email: string, iden: string, creation_time: string, creation_order: bigint, last_login_time: string, avatar: string, description: string, bio: string, profile_show: Array<string>, };
