// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmissionItem } from "./SubmissionItem";

/**
 * 用户提交属性（批量更新用）
 */
export type UserSubmissionProp = { user_id: bigint, ws_id: string | null, submissions: Array<SubmissionItem>, task_id: bigint | null, };
