// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VjudgeNodePublic = { platform: string, verified_code: string, verified: boolean, iden: string, creation_time: string, updated_at: string, remote_mode: string, };
