// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VjudgeNodePrivateRaw } from "./VjudgeNodePrivateRaw";
import type { VjudgeNodePublicRaw } from "./VjudgeNodePublicRaw";

export type VjudgeNodeRaw = { public: VjudgeNodePublicRaw, private: VjudgeNodePrivateRaw, };
