// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VjudgeTaskNodePublic = { status: string, log: string, 
/**
 * 执行的服务名 (platform:operation:method)
 */
service_name: string, 
/**
 * 最终工作流状态 JSON 快照
 */
workflow_snapshot: string | null, created_at: string, updated_at: string, };
