// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VjudgeTaskWithAccount } from "./VjudgeTaskWithAccount";

/**
 * 分页查询结果
 */
export type VjudgeTaskListResult = { data: Array<VjudgeTaskWithAccount>, total: bigint, };
