// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VjudgeNodePrivate } from "./VjudgeNodePrivate";
import type { VjudgeNodePublic } from "./VjudgeNodePublic";

export type VjudgeNode = { node_id: bigint, public: VjudgeNodePublic, private: VjudgeNodePrivate, };
