// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VjudgeTaskNodePrivate } from "./VjudgeTaskNodePrivate";
import type { VjudgeTaskNodePublic } from "./VjudgeTaskNodePublic";

export type VjudgeTaskNode = { node_id: bigint, public: VjudgeTaskNodePublic, private: VjudgeTaskNodePrivate, };
