// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VjudgeTaskNode } from "./VjudgeTaskNode";

/**
 * 任务 + 关联账号信息（用于工单列表展示）
 */
export type VjudgeTaskWithAccount = { task: VjudgeTaskNode, account_node_id: bigint, platform: string, handle: string, };
