// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VjudgeTaskNodePrivateRaw } from "./VjudgeTaskNodePrivateRaw";
import type { VjudgeTaskNodePublicRaw } from "./VjudgeTaskNodePublicRaw";

export type VjudgeTaskNodeRaw = { public: VjudgeTaskNodePublicRaw, private: VjudgeTaskNodePrivateRaw, };
