// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 工作流服务信息
 */
export type WorkflowServiceInfo = { name: string, description: string, allow_description: string | null, platform: string, operation: string, method: string | null, 
/**
 * 当前可用的边缘 socket 数量
 */
available_sockets: number, 
/**
 * 来源: "legacy" = 旧系统, "workflow" = 新工作流
 */
source: string, 
/**
 * 输入要求（requiredKeys 等）
 */
import_require: any | null, 
/**
 * 输出描述
 */
export_describe: any[] | null, };
