// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowValueDTO } from "./WorkflowValueDTO";

/**
 * 工作流状态数据 DTO
 */
export type WorkflowStatusDataDTO = { 
/**
 * 键值对数据
 */
values: { [key in string]: WorkflowValueDTO }, };
