// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 终点参数信息
 */
export type WorkflowTargetParamInfo = { 
/**
 * 参数名
 */
key: string, 
/**
 * 参数类型
 */
value_type: string, 
/**
 * 是否必须
 */
required: boolean, };
