// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowStatusDataDTO } from "./WorkflowStatusDataDTO";

/**
 * 工作流任务请求
 */
export type WorkflowTaskRequest = { 
/**
 * 服务名称 (platform:operation:method)
 */
service_name: string, 
/**
 * 输入状态数据
 */
input: WorkflowStatusDataDTO, 
/**
 * 超时时间（毫秒）
 */
timeout_ms: bigint | null, 
/**
 * 用户 WebSocket ID（用于实时推送）
 */
ws_id: string | null, 
/**
 * 关联的 VJudge 账号节点 ID
 */
vjudge_node_id: bigint | null, };
