// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 工作流值 DTO
 */
export type WorkflowValueDTO = { "type": "Inner", "value": string } | { "type": "String", "value": string } | { "type": "Number", "value": number } | { "type": "Bool", "value": boolean } | { "type": "List", "value": Array<WorkflowValueDTO> };
