// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 工作流任务状态查询响应
 */
export type WorkflowTaskStatusDTO = { 
/**
 * 任务 ID
 */
task_id: string, 
/**
 * 任务数据库状态
 */
db_status: string, 
/**
 * 日志
 */
log: string, 
/**
 * 创建时间
 */
created_at: string, 
/**
 * 更新时间
 */
updated_at: string, 
/**
 * 最新工作流状态缓存（如果有）
 */
workflow_status: any | null, };
