// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowTargetParamInfo } from "./WorkflowTargetParamInfo";

/**
 * 终点信息
 */
export type WorkflowTargetInfo = { 
/**
 * 终点 ID (service_name)
 */
target: string, 
/**
 * 展示名称
 */
name: string, 
/**
 * 描述
 */
description: string, 
/**
 * 允许描述（提示）
 */
allow_description: string | null, 
/**
 * 平台
 */
platform: string | null, 
/**
 * 参数定义
 */
params: Array<WorkflowTargetParamInfo>, };
