// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowStatusDataDTO } from "./WorkflowStatusDataDTO";

/**
 * 工作流任务响应
 */
export type WorkflowTaskResponseDTO = { 
/**
 * 任务是否成功
 */
success: boolean, 
/**
 * 任务 ID（用于后续状态查询和推送订阅）
 */
task_id: string | null, 
/**
 * 输出状态数据
 */
output: WorkflowStatusDataDTO | null, 
/**
 * 错误信息
 */
error: string | null, };
