"use server"
// Auto-generated TypeScript API client
// Do not edit this file manually

import { get, post, put, del } from '@/lib/http_server'
import { ApiEnvelope, unwrap } from '@/lib/http_func'

import { {{type_imports}} } from '@rmjac/api-declare'


// ==================== API Functions ====================

