// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 基础值类型
 *
 * 表示 workflow 中传递的各种基本数据类型。
 */
export type BaseValue = { "type": "String", "value": string } | { "type": "Number", "value": number } | { "type": "Int", "value": bigint } | { "type": "Bool", "value": boolean } | { "type": "List", "value": Array<BaseValue> } | { "type": "Object", "value": Record<string, unknown> } | { "type": "Null" };
