// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseValue } from "./BaseValue";

/**
 * 带信任标记的值
 *
 * 所有通过 workflow 传递的值都带有信任标记。
 * - `Untrusted`: 来自外部输入（前端用户请求等）
 * - `Trusted`: 来自后端服务内部生成
 */
export type WorkflowValue = { "trust": "Untrusted", } & ({ "type": "String", "value": string } | { "type": "Number", "value": number } | { "type": "Int", "value": bigint } | { "type": "Bool", "value": boolean } | { "type": "List", "value": Array<BaseValue> } | { "type": "Object", "value": Record<string, unknown> } | { "type": "Null" }) | { "trust": "Trusted", 
/**
 * 可选：生成此值的服务名称
 */
source: string | null, } & ({ "type": "String", "value": string } | { "type": "Number", "value": number } | { "type": "Int", "value": bigint } | { "type": "Bool", "value": boolean } | { "type": "List", "value": Array<BaseValue> } | { "type": "Object", "value": Record<string, unknown> } | { "type": "Null" }) | { "trust": "Final", } & ({ "type": "String", "value": string } | { "type": "Number", "value": number } | { "type": "Int", "value": bigint } | { "type": "Bool", "value": boolean } | { "type": "List", "value": Array<BaseValue> } | { "type": "Object", "value": Record<string, unknown> } | { "type": "Null" });
