// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowValue } from "./WorkflowValue";

/**
 * 值集合
 *
 * 管理一组带信任标记的键值对，或者表示最终状态。
 */
export type WorkflowValues = { "kind": "Values", inner: { [key in string]?: WorkflowValue }, } | { "kind": "Final", inner: WorkflowStatus, };
