// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workflow 值错误
 */
export type WorkflowValueError = { "UntrustedValue": string } | { "MissingValue": string } | { "TypeMismatch": { key: string, expected: string, actual: string, } };
