// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowValues } from "./WorkflowValues";

/**
 * Workflow 状态
 *
 * 表示工作流执行过程中的三种状态：
 * - `Running`: 正在执行中，携带当前值
 * - `Completed`: 成功完成
 * - `Failed`: 执行失败
 */
export type WorkflowStatus = { "Running": WorkflowValues } | { "Completed": { values: WorkflowValues, message: string | null, } } | { "Failed": { error: string, context: unknown, } };
