#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// 获取环境变量 EXPORT_PATH
const exportPath = process.env.EXPORT_PATH;

if (!exportPath) {
    console.error('错误: 未设置环境变量 EXPORT_PATH');
    process.exit(1);
}

// 解析目标目录路径（相对于当前工作目录）
const targetDir = path.resolve(process.cwd(), exportPath);

// interface 目录路径
const interfaceDir = path.join(targetDir, 'interface');

// 检查 interface 目录是否存在
if (!fs.existsSync(interfaceDir)) {
    console.error(`错误: interface 目录不存在: ${interfaceDir}`);
    process.exit(1);
}

// 读取 interface 目录下的所有 .ts 文件
const files = fs.readdirSync(interfaceDir)
    .filter(file => file.endsWith('.ts') && file !== 'index.ts')
    .sort();

if (files.length === 0) {
    console.warn('警告: interface 目录下没有找到 .ts 文件');
}

// 生成导出语句
const exportStatements = files.map(file => {
    const moduleName = file.replace('.ts', '');
    return `export * from "./interface/${moduleName}";`;
});

// 生成 index.ts 内容
const indexContent = `// This file is auto-generated by scripts/generate_export.js
// Do not edit manually

${exportStatements.join('\n')}
`;

// 写入 index.ts 文件
const indexPath = path.join(targetDir, 'index.ts');
fs.writeFileSync(indexPath, indexContent, 'utf-8');

console.log(`成功生成 ${indexPath}`);
console.log(`导出了 ${files.length} 个模块`);