[package]
name = "macro_db_init"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
sea-orm = "1.1.12"
syn = { version = "2.0.67", features = ["full"] }
