# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint

on: [push, pull_request]

jobs:
  eslint:
    name: Run eslint scanning

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm install

      - name: Tiptap Pro registry
        run: echo "$TIPTAP_PRO_REGISTRY" >> .npmrc
        env:
          TIPTAP_PRO_REGISTRY: ${{ secrets.TIPTAP_PRO_REGISTRY }}

      - name: Install dependencies
        run: yarn

      - name: ESLint Check
        run: yarn run lint --max-warnings 0
        continue-on-error: false
